import { ProductInput } from "@/lib/types";

export const initialProducts: ProductInput[] = [
  { producto: "3 amores", costo: "1", venta: "3" },
  { producto: "Aguacate", costo: "-", venta: "$5.00-10.00" },
  { producto: "Albahaca", costo: "1", venta: "4" },
  { producto: "Anturio", costo: "-", venta: "-" },
  { producto: "Bandera", costo: "1.5", venta: "4" },
  { producto: "Begonia", costo: "-", venta: "4" },
  { producto: "Bolsa de tierra", costo: "1", venta: "2" },
  { producto: "Calocasia", costo: "-", venta: "-" },
  { producto: "Cambray", costo: "-", venta: "3" },
  { producto: "Cenizo", costo: "1", venta: "3" },
  { producto: "Chile habanero", costo: "-", venta: "4" },
  { producto: "Chula en bolsa", costo: "0.5", venta: "2" },
  { producto: "Chula en canasta", costo: "1.75", venta: "4" },
  { producto: "Clavel en bolsa", costo: "1", venta: "4" },
  { producto: "Clavel en maceta", costo: "5", venta: "10" },
  { producto: "Coco", costo: "-", venta: "-" },
  { producto: "Cola de ardilla", costo: "-", venta: "4" },
  { producto: "Coleo", costo: "1", venta: "3" },
  { producto: "Crotos", costo: "-", venta: "4" },
  { producto: "Duranta", costo: "0.5", venta: "$0.75-$1.50" },
  { producto: "Falsa lavanda", costo: "1.5", venta: "4" },
  { producto: "Falsa menta", costo: "-", venta: "-" },
  { producto: "Falsa uva", costo: "1.5", venta: "3" },
  { producto: "Flor corona de Cristo", costo: "-", venta: "3" },
  { producto: "Flor de Jamaica", costo: "1", venta: "3" },
  { producto: "Flor de las 11 en bolsa", costo: "0.5", venta: "2" },
  { producto: "Flor de las 11 en canasta", costo: "1.75", venta: "4" },
  { producto: "Flor de muerto", costo: "0.5", venta: "2" },
  { producto: "Gardenia", costo: "-", venta: "-" },
  { producto: "Gazenia en bolsa", costo: "1", venta: "2" },
  { producto: "Gazenia en canasta", costo: "2", venta: "4" },
  { producto: "Geranios en bolsa", costo: "-", venta: "-" },
  { producto: "Geranios en canasta", costo: "2", venta: "4" },
  { producto: "Hierba buena", costo: "0.5", venta: "2" },
  { producto: "Hierba buena en canasta", costo: "1.5", venta: "3" },
  { producto: "Hortensia en bolsa", costo: "-", venta: "8" },
  { producto: "Hortensia en maceta", costo: "-", venta: "15" },
  { producto: "Jupiter", costo: "-", venta: "-" },
  { producto: "Lengua de suegra en bolsa", costo: "1", venta: "$3.00-$4.00" },
  { producto: "Lengua de suegra en maceta", costo: "5", venta: "10" },
  { producto: "Limón indio grande", costo: "-", venta: "8" },
  { producto: "Limón indio pequeño", costo: "3", venta: "6" },
  { producto: "Limón persico", costo: "3", venta: "6" },
  { producto: "Mango panadés", costo: "3", venta: "6" },
  { producto: "Mano de león", costo: "-", venta: "-" },
  { producto: "Maracuyá", costo: "1", venta: "5" },
  { producto: "Menta", costo: "-", venta: "2" },
  { producto: "Narciso", costo: "1", venta: "4" },
  { producto: "Palmera", costo: "-", venta: "7" },
  { producto: "Romero", costo: "1", venta: "3" },
  { producto: "Rosa en bolsa", costo: "1", venta: "3" },
  { producto: "Rosa en maceta", costo: "5", venta: "10" },
  { producto: "Ruda", costo: "1", venta: "3" },
  { producto: "Sábila en bolsa", costo: "-", venta: "-" },
  { producto: "Sábila en maceta", costo: "5", venta: "8" },
  { producto: "San José", costo: "1", venta: "-" },
  { producto: "Tulla", costo: "1", venta: "3" },
  { producto: "Veranera en bolsa", costo: "3", venta: "$5.00-$8.00" },
  { producto: "Veranera en maceta", costo: "5", venta: "10" },
  { producto: "Zebrina en canasta", costo: "-", venta: "6" },
];
